### ISSUE TITLE
Adding shell to 7490 firmware

### ISSUE THREAD

**Issue by jekkos** [PeterPawn/YourFritz#17]
Hi there, really cool project you have here!
I'm trying to add a shell to a 7490 firmware, which is specifically made for Belgium ISP

Issuing the following command

` TOOLBOX_IMAGE_SIZE=3 ./build_shellinabox_implant_image -d FRITZ.Box_7490.en-de-es-it-fr-pl.113.06.53.image > 7490.image `

this gives me this output

```
Using binaries for systems with kernel version 3.10.73.
A TI checksum signature was found on './var/tmp/kernel.image', file will be truncated by 8 byte.
```

But the final file is way smaller than the original (5MB instead of 23MB) and also I can't flash it through the browser (as it says it's invalid). Any idea how I can debug this further? Eg which files should be present in the archive and how can I dissect it?

Thanks

**Comment by PeterPawn** [comment]
The created image is intended to be loaded and started once ... it will "inject" the needed files into the original system. Therefore it may not be loaded via GUI and is somewhat smaller, because it does not need all of AVM's own components.

To get an idea how it works, you may read this post of mine: https://www.ip-phone-forum.de/threads/modfs-squashfs-image-avm-firmware-%C3%A4ndern-f%C3%BCr-nand-basierte-fritz-boxen.273304/page-80#post-2299737 - try to use Google Translator, if you're unable to read it in German.

Please use the linked board for further questions ... there's also another thread about this theme, which was/is mentioned here: https://github.com/PeterPawn/first_aid/blob/master/README.md

I'll close this here ... it's not really an issue and such questions are better placed at the board mentioned above, because more people may (and will) read the answers.
