### ISSUE TITLE
eva_discover calling non-existent function yf_get_ip_addresses

### ISSUE THREAD

**Issue by MAnantharaman** [PeterPawn/YourFritz#3]
The title says it all - and easy to fix with attached change - but makes me wonder who has actually used the current version;-)

Still not able to access EVA in my 7490 - maybe I can understand the analysis in http://www.ip-phone-forum.de/showthread.php?t=289201 to get it working ...

Regards, Martin
[git.diff.zip](https://github.com/PeterPawn/YourFritz/files/768312/git.diff.zip)

**Comment by PeterPawn** [comment]
There were no (profound) steps since the first commit and that means, it's still a preview or a (working) proof-of-concept, but you have to specify the parameters yourself.

The whole part for automatic detection of default values for unspecified parameters is very incomplete and wasn't changed in the last year.

My comment in the IPPF thread (see first version for the link) regarding this script was:

> Ich habe das "eva_discover" mal informationshalber eingecheckt und es funktioniert auch, wenn man alle Parameter beim Aufruf komplett angibt (eva_discover FROM=192.168.178.2 TO=192.168.178.1 WAIT=10 BLIP=1 HOLD=1) ... im Moment fehlt da allerdings noch etwas bei der Parametrierung bzw. beim automatischen Ermitteln von nicht angegebenen Werten [...]

There nothing to add until now. I simply had no time to implement a complete (or more sophisticated) logic to "guess" default values for omitted parameters.

If you'd like to use a better commented version, you could use the PowerShell script with the same functionality.

Your patch would only fix a smaller problem and all other detections still aren't working - the recommendation or summary "You'd better specify all parameters yourself." wouldn't change.

If you'd like to implement the detection for the other settings too, drop me a note and we can coordinate the ideas how it is to realize.

**Comment by PeterPawn** [comment]
Feel free to reopen this issue, but I'd prefer to ignore your patch - I'm still thinking, but it could be a better idea to disable the whole code from line 316 up to 371, because it was never tested yet and the wrong function name is surely not the only fault.

**Comment by MAnantharaman** [comment]
That's OK - and you are right to repeat ever so often that one should not have unrealistic expectations of such young (and fairly extensive) code. BTW: I have found that with my FB 7490 eva_discover with HOLD=1 does not interrupt the boot-sequence in such a way that one can access ADAM2 (get "acccess denied" with ftp, socat, etc.) - whether with default 192.168.178.1 or (my current) 192.168.0.1 network-setup. At the same time the trick you published on using a recovery image for another box works perfectly! So I do not intend to pursue a solution rather hope to be able to use the trick on my Linux box tooo (with Wine) ...

**Comment by PeterPawn** [comment]
I've changed the "eva_discover" script later to replace the "QUIT" command with a simple "end of input", because my 6490 device shows the same behaviour (the FTP server doesn't accept any new connection, but the loader code is still active and the boot process doesn't continue), if I had sent this final "QUIT" to terminate the FTP session the "right" way. I've never tested it (that means "HOLD=1") again with a 7490, because I use it mostly in conjunction with other scripts and these additional steps follow the discovery process immediately. If you do not initiate a FTP session from "eva_discover" (the HOLD=1 option is the only reason for such a session from here), there's no problem to connect to the device after it was found by "eva_discover", as long as the connection is made "in time". It looks like different models (and different boot loader versions) show a slightly different behavior here - you could try to revert the change to the "nc" call connecting on port 21 of the target and re-add the "QUIT" command (the RFC recommends it and the 6490 was the first device, where I've discovered a problem with it).
