### ISSUE TITLE
Anyway to get Telnet working on new firmware ? 

### ISSUE THREAD

**Issue by MasterCATZ** [PeterPawn/YourFritz#4]
https://avm.de/fileadmin/user_upload/DE/Labor/Download/fritzbox-7490-labor-46493_Netz.zip

how would I go about getting telnet inside this firmware ?

I tried using TelefonSparbuch_Telnet04.30.tar but did not seem to work

**Comment by PeterPawn** [comment]
Ausgehend von der deutschen Firmware (die enthält nur die deutsche Sprachversion des GUI) unterstelle ich hier mal das Verständnis der deutschen Sprache und dann ist das IPPF (www.ip-phone-forum.de) die beste Anlaufstelle für solche Fragen. 

Dort ist auch (mehrfach) beschrieben, wie das Entpacken, Ändern und Packen von Firmware-Images funktioniert und was zu tun ist, um die (im Anschluß erst einmal unsignierte) eigene Firmware-Version auf die Box zu bringen. Es gibt da durchaus mehrere denkbare Lösungen.

Im Branch "binaries" in diesem Repository sind dann tatsächlich auch einige (Linux-)Programme zu finden, die einem dabei hilfreich sein könnten.

Bei einer "frischen" Box (also ohne bisherige Änderungen) würde ich erst mal den Start einer Shell über Zusätze im YAFFS2-Filesystem bewirken (wie das geht, ist im IPPF unter dem Stichwort "modfs-Starter" zu finden, auch wenn es nicht mehr einfach durch den Upload eines Images funktioniert, wie das bis einschließlich 06.50 der Fall war) und anschließend mit "modfs" (auch dafür gibt es einen Thread im IPPF) arbeiten oder man kann auch gleich mit Freetz (dem Original oder einem Fork) ein Image erzeugen, welches man dann über den Bootloader installiert.

Welchen Weg man wählen sollte, hängt u.a. auch vom Umfang der geplanten Änderungen ab und wie dicht man mit der eigenen Firmware am AVM-Original bleiben will.

If you're really unable to read/write in German, drop me a note and I'll answer in English - but due to limitations of the mentioned firmware version (its GUI isn't available in English) I'd assume, that your German skills are enough, to follow even the discussions on www.ip-phone-forum.de, where those themes are present (and explained more then once) already.

**Comment by MasterCATZ** [comment]
Ok thanks , so far my attempts have lead to fritzbox refusing to use the modified file saying it is not an official AVM firmware 
I really want 6.90 with Telnet

**Comment by PeterPawn** [comment]
Do not try to install the modified firmware via AVM's "Datei-Update" function ... use the direct method via EVA bootloader to load and start the own image - it will install itself into the flash memory after this start and reboot the device again, to run with the new firmware from flash now.

If you use this way, no signature check is performed (it's the reason for the "not an official AVM firmware" error) and you may install any firmware ... even an unsigned one (and even a firmware with severe malfunctions).
